# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78a25ee0d9ea2a3a93504e50c5a825794d8c8d216f39dfd9421d76249a91903bdd1a39dec9168bbc99804487c21b4d46a03568ea62704af067d415a00131fd3e

test:
  secret_key_base: f579b7bf850f517f2c2fc33db11fef756a6d084f1716c0130c14e1a1445664664e76139466a88786f180d26527dd1f91cac1d0cf5b5d17b3bc67ee2aaece2f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER__KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_SECRET"] %>
